import cozyFire from "../../public/cozyfire.jpg";
import { Geist, Geist_Mono } from "next/font/google";
import { Boundary } from "./components/Error/Boundary"
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="App" style={{ backgroundImage: cozyFire }}>
          <header className="App-header"></header>
          <span className="Grid-flex">
            <Boundary>
              {children}
            </Boundary>
          </span>
        </div>
      </body>
    </html>
  );
}
